
pipeline {
    agent any
    stages {
        stage('CodeCheckOut') {
            steps {
                script {
                    checkout scm
                }
            }
        }
        stage('Build Customer app code') {
            steps {
                script {
                    def javaHome = tool 'JAVA_1.8'
                    def mvnHome = tool 'maven-3'
                }
            }
        }
    }   
}
